server:
  port: 8443

app.broker:
  configs:
    local:
      queueManager: QM1
      channel: DEV.APP.SVRCONN
      connName: localhost(1414)
      user: app
      password: passw0rd
      sslClipherSuite: ""
      request: DEV.QUEUE.1
#      response: RESPONSE.QUEUE